Use 1.12.x branch on Docker github repository
This is because the current HEAD of Docker GitHub repository file not
contain "mflg". So, the error below occurred.

Step 6 : RUN go get -d -tags pam github.com/tg123/sshpiper/sshpiperd
 ---> Running in d3300302a15d
package github.com/docker/docker/pkg/mflag: cannot find package "github.com/docker/docker/pkg/mflag" in any of:
	/usr/local/go/src/github.com/docker/docker/pkg/mflag (from $GOROOT)
	/go/src/github.com/docker/docker/pkg/mflag (from $GOPATH)
ERROR: Service 'sshpiperd' failed to build: The command '/bin/sh -c go get -d -tags pam github.com/tg123/sshpiper/sshpiperd' returned a non-zero code: 1